env:
  es6: true
  node: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  {
    "quotes": 0,
    "linebreak-style": 0,
    "comma-dangle": 0,
    "object-curly-newline": 0,
    "import/prefer-default-export": 0,
    "arrow-parens": 0,
    "nonblock-statement-body-position": 0,
    "curly": 0,
    "func-names": 0,
    "space-before-function-paren": 0,
    "no-confusing-arrow": 0,
    "implicit-arrow-linebreak": 0,
    "no-useless-escape": 0,
    "no-dupe-keys": 0,
    "indent": 0,
    "class-methods-use-this": 0,
    "no-param-reassign": 0,
  }
